# Use `rake secret` to generate one key
SECRET_KEY_BASE: ''

# domain name used by action cable
DOMAIN: ''
PROTOCOL: http

# UPYUN set
UPYUN_USERNAME: ''
UPYUN_PASSWORD: ''
UPYUN_BUCKET: ''
UPYUN_BUCKET_HOST: ''

# sidekiq namespace
SIDEKIQ_NAMESPACE: ''

WX_WEAPP_APPID: 'wx1e0de85fe9cd765e'
WX_WEAPP_APPSECRET: 'a81a37aba2ce9e09257afd6e9f7c9e36'
